import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "getting-started",
    {
      type: 'category',
      label: 'Intro to SupraMD',
      items: [{ type: 'autogenerated', dirName: 'intro' }],
    },
    {
      type: 'category',
      label: 'Build SupraMD',
      items: [{ type: 'autogenerated', dirName: 'build' }],
    },
    {
      type: 'category',
      label: 'Run SupraMD',
      items: [{ type: 'autogenerated', dirName: 'run' }],
    },
    {
      type: 'category',
      label: 'Config SupraMD',
      items: [{ type: 'autogenerated', dirName: 'config' }],
    },
  ],
  reference: [{type: 'autogenerated', dirName: 'reference'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
